length:
  digit_3: 3
  digit_255: 255
  digit_6: 6
number_10: 10
size_50: 50
format_img: ["image/png", "image/jpg", "image/jpeg"]
img:
  size_arr_500: [500, 500]
  size_50: 50
less_than_5: 5
size_80: 80
checked_1: "1"